// Generated by gencpp from file motor_control/Floats_array.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_MESSAGE_FLOATS_ARRAY_H
#define MOTOR_CONTROL_MESSAGE_FLOATS_ARRAY_H

#include <ros/service_traits.h>


#include <motor_control/Floats_arrayRequest.h>
#include <motor_control/Floats_arrayResponse.h>


namespace motor_control
{

struct Floats_array
{

typedef Floats_arrayRequest Request;
typedef Floats_arrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Floats_array
} // namespace motor_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor_control::Floats_array > {
  static const char* value()
  {
    return "0224123962c7a33069a097b5e752decf";
  }

  static const char* value(const ::motor_control::Floats_array&) { return value(); }
};

template<>
struct DataType< ::motor_control::Floats_array > {
  static const char* value()
  {
    return "motor_control/Floats_array";
  }

  static const char* value(const ::motor_control::Floats_array&) { return value(); }
};


// service_traits::MD5Sum< ::motor_control::Floats_arrayRequest> should match
// service_traits::MD5Sum< ::motor_control::Floats_array >
template<>
struct MD5Sum< ::motor_control::Floats_arrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor_control::Floats_array >::value();
  }
  static const char* value(const ::motor_control::Floats_arrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_control::Floats_arrayRequest> should match
// service_traits::DataType< ::motor_control::Floats_array >
template<>
struct DataType< ::motor_control::Floats_arrayRequest>
{
  static const char* value()
  {
    return DataType< ::motor_control::Floats_array >::value();
  }
  static const char* value(const ::motor_control::Floats_arrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor_control::Floats_arrayResponse> should match
// service_traits::MD5Sum< ::motor_control::Floats_array >
template<>
struct MD5Sum< ::motor_control::Floats_arrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor_control::Floats_array >::value();
  }
  static const char* value(const ::motor_control::Floats_arrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_control::Floats_arrayResponse> should match
// service_traits::DataType< ::motor_control::Floats_array >
template<>
struct DataType< ::motor_control::Floats_arrayResponse>
{
  static const char* value()
  {
    return DataType< ::motor_control::Floats_array >::value();
  }
  static const char* value(const ::motor_control::Floats_arrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_CONTROL_MESSAGE_FLOATS_ARRAY_H
